services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 127.0.0.1:5432:5432
    shm_size: 1g
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      DB_POOL_MAX_CONNS: ${DB_POOL_MAX_CONNS:-100}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    logging:
      driver: none
